-- 1. Display the number of states present in the LocationTable
SELECT COUNT(DISTINCT State) AS 'NO. OF STATES' FROM Location; [cite: 147]

-- 2. How many products are of regular type?
SELECT COUNT(DISTINCT Product) AS 'NO. OF REGULAR' FROM Product WHERE Type = 'Regular'; [cite: 150]

-- 3. How much spending has been done on marketing of product ID 1?
SELECT SUM(Marketing) AS 'Total_Marketing_Spending' FROM Fact WHERE ProductId = 1; [cite: 152]

-- 4. What is the minimum sales of a product?
SELECT MIN(Sales) FROM Fact; [cite: 154]

-- 5. Display the max cost of goods sold (COGS)
SELECT MAX(COGS) FROM Fact; [cite: 156]

-- 6. Display the details of product where product type is coffee
SELECT * FROM Product WHERE Product_Type = 'Coffee'; [cite: 158]

-- 7. Display the details where the total expenses are greater than 40
SELECT * FROM Fact WHERE Total_Expenses > 40; [cite: 160]

-- 8. What is the average sales in the area code 719?
SELECT AVG(Sales) FROM Fact WHERE Area_Code = 719; [cite: 119]

-- 9. Find out the total profit generated by Colorado State
SELECT SUM(Profit) AS 'Total_Profit' 
FROM Fact F 
INNER JOIN Location L ON F.Area_Code = L.Area_Code 
WHERE L.State = 'Colorado'; [cite: 120]

-- 10. Display the average inventory for each product id
SELECT ProductId, AVG(Inventory) AS 'AVG. Inventory' FROM Fact GROUP BY ProductId;

-- 11. Display state in a sequential order in Location Table
SELECT DISTINCT State FROM Location ORDER BY State;

-- 12. Display the productId where average profit is greater than 100
SELECT ProductId, AVG(Profit) FROM Fact GROUP BY ProductId HAVING AVG(Profit) > 100;

-- 13. Display the details of the Fact Table on 2010-01-01
SELECT * FROM Fact WHERE Date = '2010-01-01';

-- 14. Display the date, productid, sales, and profit in descending order of date
SELECT Date, ProductId, Sales, Profit FROM Fact ORDER BY Date DESC;

-- 15. Display productid, product_type, sales, and profit
SELECT P.ProductId, P.Product_Type, F.Sales, F.Profit 
FROM Product P 
INNER JOIN Fact F ON P.ProductId = F.ProductId;